"""Add MedicationAdministration model for MAR

Revision ID: 06bd2b65aa0d
Revises: 1a40721d4a92
Create Date: 2025-06-06 23:36:38.627210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bd2b65aa0d'
down_revision = '1a40721d4a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication_administrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('patient_medication_id', sa.String(length=36), nullable=False),
    sa.Column('administered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('administration_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('dose_given', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['administered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_administrations_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_administrations_patient_medication_id'), ['patient_medication_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_administrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_administrations_patient_medication_id'))
        batch_op.drop_index(batch_op.f('ix_medication_administrations_patient_id'))

    op.drop_table('medication_administrations')
    # ### end Alembic commands ###
