"""Add dose range to OrderableItem

Revision ID: 1a40721d4a92
Revises: 19667bb0c731
Create Date: 2025-06-06 23:21:01.241471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a40721d4a92'
down_revision = '19667bb0c731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderable_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_dose', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_dose', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('default_dose_unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orderable_items', schema=None) as batch_op:
        batch_op.drop_column('default_dose_unit')
        batch_op.drop_column('max_dose')
        batch_op.drop_column('min_dose')

    # ### end Alembic commands ###
